version : 2
mergeable :
  - when : pull_request.*
    varidate :
      # WIP から始まるプルリクエストをマージできないようにする
      - do : title
        must_exclude : 
          regex : ^\[WIP\]
      # wip ラベルが付いているプルリクエストをマージできないようにする
      - do : label
        must_exclude : 
          regex : 'wip'
