version : 2
mergeable :
  - when : pull_request.*
    validate :
      - do : title # WIP または [WIP] から始まるプルリクエストをマージできないようにする
        must_exclude : 
          regex : ^WIP|^\[WIP\]
      - do : label # wip ラベルが付いているプルリクエストをマージできないようにする
        must_exclude : 
          regex : 'wip'
