version : 2
mergeable :
  - when : pull_request.*
    varidate :
      - do : title # WIP から始まるプルリクエストをマージできないようにする
        must_exclude : 
          regex : ^\[WIP\]
      - do : label # wip ラベルが付いているプルリクエストをマージできないようにする
        must_exclude : 
          regex : 'wip'
